// Code generated by MockGen. DO NOT EDIT.

package product_service_mocks

import (
	context "context"
	reflect "reflect"

	product_dto "github.com/celio001/product-command/internal/fiber/v1/product/dto"
	fiscal "github.com/celio001/product-command/internal/modules/fiscal"
	inventory "github.com/celio001/product-command/internal/modules/inventory"
	product "github.com/celio001/product-command/internal/modules/product"
	"github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

type MockProductSvcInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProductSvcInterfaceMockRecorder
	isgomock struct{}
}

type MockProductSvcInterfaceMockRecorder struct {
	mock *MockProductSvcInterface
}

func NewMockProductSvcInterface(ctrl *gomock.Controller) *MockProductSvcInterface {
	mock := &MockProductSvcInterface{ctrl: ctrl}
	mock.recorder = &MockProductSvcInterfaceMockRecorder{mock}
	return mock
}

func (m *MockProductSvcInterface) EXPECT() *MockProductSvcInterfaceMockRecorder {
	return m.recorder
}

func (m *MockProductSvcInterface) CreateProductSvc(ctx context.Context, p product.Product, i inventory.Inventory, f fiscal.FiscalData) (product_dto.CreateProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductSvc", ctx, p, i, f)
	ret0, _ := ret[0].(product_dto.CreateProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProductSvcInterfaceMockRecorder) CreateProductSvc(ctx, p, i, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductSvc", reflect.TypeOf((*MockProductSvcInterface)(nil).CreateProductSvc), ctx, p, i, f)
}

func (m *MockProductSvcInterface) SoftDeleteProductSvc(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteProductSvc", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockProductSvcInterfaceMockRecorder) SoftDeleteProductSvc(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteProductSvc", reflect.TypeOf((*MockProductSvcInterface)(nil).SoftDeleteProductSvc), ctx, id)
}
