name: CI Check Product Command

on:
  pull_request:
    branches:
      - main
    paths:
      - 'product-command/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          context: ./product-command
          push: false
          go-version-file: product-command/go.mod

      - name: Instalar dependências
        run: go mod download
        working-directory: product-command

      - name: Executar testes unitários
        run: go test ./... -v -coverprofile=coverage.out
        working-directory: product-command

  validate-image:
    depends-on: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Teste de Build da Imagem (Dry Run)
        uses: docker/build-push-action@v5
        with:
          context: ./product-command
          push: false