name: CI Check Product Query

on:
  pull_request:
    branches:
      - main
    paths:
      - 'product-query/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version-file: product-query/go.mod

      - name: Instalar dependências
        run: go mod download
        working-directory: product-query

      - name: Executar testes unitários
        run: go test ./... -v -coverprofile=coverage.out
        working-directory: product-query
  validate-image:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Teste de Build da Imagem (Dry Run)
        uses: docker/build-push-action@v5
        with:
          context: ./product-query
          push: false